### ISSUE TITLE
Several card names incomplete

### ISSUE THREAD

**Issue by ALiteralCommunist** [Sebaestschjin/octgn-lotr#1]
Just looking through the Fellowship of the Ring set, I noticed a bunch of cards with incomplete names. There are six different cards named "Saruman" in the deck builder, but should be named "Saruman's Ambition", "Saruman's Chill", etc. It appears that any cards with an apostrophe have their names (and subnames) cut off at the apostrophe, so it might be an issue when the names were pulled from a database using a script.

**Comment by Sebaestschjin** [comment]
Good catch, didn't realize this in my tests.
The names are imported from a script I'll check why it's having problems with the ' and update it. Should be easy to fix.
